# Stage 1: build
FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_LOG_LEVEL
ARG VITE_USE_REDIS
ARG VITE_REDIS_URL
ARG VITE_REDIS_TOKEN
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_LOG_LEVEL=$VITE_LOG_LEVEL
ENV VITE_USE_REDIS=$VITE_USE_REDIS
ENV VITE_REDIS_URL=$VITE_REDIS_URL
ENV VITE_REDIS_TOKEN=$VITE_REDIS_TOKEN
COPY package*.json ./
RUN npm ci --frozen-lockfile
COPY . .
RUN npm run build

# Stage 2: serve
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
