# Stage 1: build
FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_LOG_LEVEL
ARG VITE_USE_REDIS
ARG VITE_REDIS_URL
ARG VITE_REDIS_TOKEN
ARG VITE_LOGO_WIDTH
ARG VITE_LOGO_HEIGHT
ARG VITE_SUPPORT_EMAIL
ARG VITE_SUPPORT_WHATSAPP
ARG VITE_PLAN_PRICE_MONTHLY
ARG VITE_PLAN_PRICE_ANNUAL
ARG VITE_PLAN_FEATURES_MONTHLY
ARG VITE_PLAN_FEATURES_ANNUAL
ARG VITE_TERMS_URL
ARG VITE_PRIVACY_URL
ARG VITE_TEMPLATE_VARIANT
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_LOG_LEVEL=$VITE_LOG_LEVEL
ENV VITE_USE_REDIS=$VITE_USE_REDIS
ENV VITE_REDIS_URL=$VITE_REDIS_URL
ENV VITE_REDIS_TOKEN=$VITE_REDIS_TOKEN
ENV VITE_LOGO_WIDTH=$VITE_LOGO_WIDTH
ENV VITE_LOGO_HEIGHT=$VITE_LOGO_HEIGHT
ENV VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
ENV VITE_SUPPORT_WHATSAPP=$VITE_SUPPORT_WHATSAPP
ENV VITE_PLAN_PRICE_MONTHLY=$VITE_PLAN_PRICE_MONTHLY
ENV VITE_PLAN_PRICE_ANNUAL=$VITE_PLAN_PRICE_ANNUAL
ENV VITE_PLAN_FEATURES_MONTHLY=$VITE_PLAN_FEATURES_MONTHLY
ENV VITE_PLAN_FEATURES_ANNUAL=$VITE_PLAN_FEATURES_ANNUAL
ENV VITE_TERMS_URL=$VITE_TERMS_URL
ENV VITE_PRIVACY_URL=$VITE_PRIVACY_URL
ENV VITE_TEMPLATE_VARIANT=$VITE_TEMPLATE_VARIANT
COPY package*.json ./
RUN npm ci --frozen-lockfile
COPY . .
RUN npm run build

# Stage 2: serve
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
