version: '3.8'

services:
  landing:
    image: ghcr.io/devsandovalbezerra/poupeja-landing:latest
    networks:
      - network_public
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
      labels:
        - "traefik.enable=1"
        - "traefik.http.routers.landing.rule=Host(`app360.mercantilizar.com.br`)"
        - "traefik.http.routers.landing.entrypoints=websecure"
        - "traefik.http.routers.landing.priority=1"
        - "traefik.http.routers.landing.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.landing.service=landing"
        - "traefik.http.services.landing.loadbalancer.server.port=80"
        - "traefik.http.services.landing.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.landing-http.rule=Host(`app360.mercantilizar.com.br`)"
        - "traefik.http.routers.landing-http.entrypoints=web"
        - "traefik.http.routers.landing-http.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

networks:
  network_public:
    external: true
